spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 10
#      idle-timeout: 300000
#      max-lifetime: 1800000
#      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    defer-datasource-initialization: true
logging:
  level:
    fr.revoicechat: debug
    logging.level.org.hibernate.SQL: debug
    logging.level.org.hibernate.type.descriptor.sql: debug
